export const GET_RECEIPT_BY_ID_REQUEST = "GET_RECEIPT_BY_ID_REQUEST";
export const GET_RECEIPT_BY_ID_SUCCESS = "GET_RECEIPT_BY_ID_SUCCESS";
export const GET_RECEIPT_BY_ID_FAILURE = "GET_RECEIPT_BY_ID_FAILURE";

export const GET_RECEIPTS_BY_COMPANY_ID_REQUEST = "GET_RECEIPT_BY_CSOMPANY_ID_REQUEST";
export const GET_RECEIPTS_BY_COMPANY_ID_SUCCESS = "GET_RECEIPT_BY_CSOMPANY_ID_SUCCESS";
export const GET_RECEIPTS_BY_COMPANY_ID_FAILURE = "GET_RECEIPT_BY_CSOMPANY_ID_FAILURE";

export const GET_RECEIPTS_BY_DAY_REQUEST = "GET_RECEIPTS_BY_DAY_REQUEST";
export const GET_RECEIPTS_BY_DAY_SUCCESS = "GET_RECEIPTS_BY_DAY_SUCCESS";
export const GET_RECEIPTS_BY_DAY_FAILURE = "GET_RECEIPTS_BY_DAY_FAILURE";

export const GET_RECEIPTS_BY_MONTH_REQUEST = "GET_RECEIPTS_BY_MONTH_REQUEST";
export const GET_RECEIPTS_BY_MONTH_SUCCESS = "GET_RECEIPTS_BY_MONTH_SUCCESS";
export const GET_RECEIPTS_BY_MONTH_FAILURE = "GET_RECEIPTS_BY_MONTH_FAILURE";