export const GET_CART_BY_ID_REQUEST = "GET_CART_BY_ID_REQUEST";
export const GET_CART_BY_ID_SUCCESS = "GET_CART_BY_ID_SUCCESS";
export const GET_CART_BY_ID_FAILURE = "GET_CART_BY_ID_FAILURE";

export const GET_CART_BY_BASKET_ID_REQUEST = "GET_CART_BY_BASKET_ID_REQUEST";
export const GET_CART_BY_BASKET_ID_SUCCESS = "GET_CART_BY_BASKET_ID_SUCCESS";
export const GET_CART_BY_BASKET_ID_FAILURE = "GET_CART_BY_BASKET_ID_FAILURE";

export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_FAILURE = "CREATE_CART_FAILURE";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILURE = "UPDATE_CART_FAILURE";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILURE = "DELETE_CART_FAILURE";

export const ADD_PRODUCT_TO_CART_REQUEST = "ADD_PRODUCT_TO_CART_REQUEST";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";
export const ADD_PRODUCT_TO_CART_FAILURE = "ADD_PRODUCT_TO_CART_FAILURE";

export const UPDATE_CART_PRODUCT_REQUEST = "UPDATE_CART_PRODUCT_REQUEST";
export const UPDATE_CART_PRODUCT_SUCCESS = "UPDATE_CART_PRODUCT_SUCCESS";
export const UPDATE_CART_PRODUCT_FAILURE = "UPDATE_CART_PRODUCT_FAILURE";

export const DELETE_CART_PRODUCT_REQUEST = "DELETE_CART_PRODUCT_REQUEST";
export const DELETE_CART_PRODUCT_SUCCESS = "DELETE_CART_PRODUCT_SUCCESS";
export const DELETE_CART_PRODUCT_FAILURE = "DELETE_CART_PRODUCT_FAILURE";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE";