export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS";
export const GET_ORDER_BY_ID_FAILURE = "GET_ORDER_BY_ID_FAILURE";

export const GET_ORDER_BY_BASKET_ID_REQUEST = "GET_ORDER_BY_BASKET_ID_REQUEST";
export const GET_ORDER_BY_BASKET_ID_SUCCESS = "GET_ORDER_BY_BASKET_ID_SUCCESS";
export const GET_ORDER_BY_BASKET_ID_FAILURE = "GET_ORDER_BY_BASKET_ID_FAILURE";

export const GET_ORDERS_BY_COMPANY_ID_REQUEST = "GET_ORDERS_BY_COMPANY_ID_REQUEST";
export const GET_ORDERS_BY_COMPANY_ID_SUCCESS = "GET_ORDERS_BY_COMPANY_ID_SUCCESS";
export const GET_ORDERS_BY_COMPANY_ID_FAILURE = "GET_ORDERS_BY_COMPANY_ID_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const CREATE_ORDER_BY_CART_REQUEST = "CREATE_ORDER_BY_CART_REQUEST";
export const CREATE_ORDER_BY_CART_SUCCESS = "CREATE_ORDER_BY_CART_SUCCESS";
export const CREATE_ORDER_BY_CART_FAILURE = "CREATE_ORDER_BY_CART_FAILURE";
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAILURE = "UPDATE_ORDER_FAILURE";

export const UPDATE_ORDER_BY_CART_REQUEST = "UPDATE_ORDER_BY_CART_REQUEST";
export const UPDATE_ORDER_BY_CART_SUCCESS = "UPDATE_ORDER_BY_CART_SUCCESS";
export const UPDATE_ORDER_BY_CART_FAILURE = "UPDATE_ORDER_BY_CART_FAILURE";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";

export const PAY_ALL_ORDERS_REQUEST = "PAY_ALL_ORDERS_REQUEST";
export const PAY_ALL_ORDERS_SUCCESS = "PAY_ALL_ORDERS_SUCCESS";
export const PAY_ALL_ORDERS_FAILURE = "PAY_ALL_ORDERS_FAILURE";

export const PAY_SELECTED_ORDERS_REQUEST = "PAY_SELECTED_ORDERS_REQUEST";
export const PAY_SELECTED_ORDERS_SUCCESS = "PAY_SELECTED_ORDERS_SUCCESS";
export const PAY_SELECTED_ORDERS_FAILURE = "PAY_SELECTED_ORDERS_FAILURE";

export const PAY_AMOUNT_REQUEST = "PAY_AMOUNT_REQUEST";
export const PAY_AMOUNT_SUCCESS = "PAY_AMOUNT_SUCCESS";
export const PAY_AMOUNT_FAILURE = "PAY_AMOUNT_FAILURE";

export const TRANSFER_ORDERS_REQUEST = "TRANSFER_ORDERS_REQUEST";
export const TRANSFER_ORDERS_SUCCESS = "TRANSFER_ORDERS_SUCCESS";
export const TRANSFER_ORDERS_FAILURE = "TRANSFER_ORDERS_FAILURE";