export const CREATE_BASKET_CATEGORY_REQUEST = "CREATE_BASKET_CATEGORY_REQUEST";
export const CREATE_BASKET_CATEGORY_SUCCESS = "CREATE_BASKET_CATEGORY_SUCCESS";
export const CREATE_BASKET_CATEGORY_FAILURE = "CREATE_BASKET_CATEGORY_FAILURE";

export const UPDATE_BASKET_CATEGORY_REQUEST = "UPDATE_BASKET_CATEGORY_REQUEST";
export const UPDATE_BASKET_CATEGORY_SUCCESS = "UPDATE_BASKET_CATEGORY_SUCCESS";
export const UPDATE_BASKET_CATEGORY_FAILURE = "UPDATE_BASKET_CATEGORY_FAILURE";

export const DELETE_BASKET_CATEGORY_REQUEST = "DELETE_BASKET_CATEGORY_REQUEST";
export const DELETE_BASKET_CATEGORY_SUCCESS = "DELETE_BASKET_CATEGORY_SUCCESS";
export const DELETE_BASKET_CATEGORY_FAILURE = "DELETE_BASKET_CATEGORY_FAILURE";