export const GET_REPORT_BY_DAY_REQUEST = "GET_REPORT_BY_DAY_REQUEST";
export const GET_REPORT_BY_DAY_SUCCESS = "GET_REPORT_BY_DAY_SUCCESS";
export const GET_REPORT_BY_DAY_FAILURE = "GET_REPORT_BY_DAY_FAILURE";

export const GET_REPORT_BY_MONTH_REQUEST = "GET_REPORT_BY_MONTH_REQUEST";
export const GET_REPORT_BY_MONTH_SUCCESS = "GET_REPORT_BY_MONTH_SUCCESS";
export const GET_REPORT_BY_MONTH_FAILURE = "GET_REPORT_BY_MONTH_FAILURE";

export const GET_REPORT_BY_YEAR_REQUEST = "GET_REPORT_BY_YEAR_REQUEST";
export const GET_REPORT_BY_YEAR_SUCCESS = "GET_REPORT_BY_YEAR_SUCCESS";
export const GET_REPORT_BY_YEAR_FAILURE = "GET_REPORT_BY_YEAR_FAILURE";

export const GET_REPORTS_BY_MONTH_REQUEST = "GET_REPORTS_BY_MONTH_REQUEST";
export const GET_REPORTS_BY_MONTH_SUCCESS = "GET_REPORTS_BY_MONTH_SUCCESS";
export const GET_REPORTS_BY_MONTH_FAILURE = "GET_REPORTS_BY_MONTH_FAILURE";

export const GET_REPORT_BY_SELECTED_DAY_REQUEST = "GET_REPORT_BY_SELECTED_DAY_REQUEST";
export const GET_REPORT_BY_SELECTED_DAY_SUCCESS = "GET_REPORT_BY_SELECTED_DAY_SUCCESS";
export const GET_REPORT_BY_SELECTED_DAY_FAILURE = "GET_REPORT_BY_SELECTED_DAY_FAILURE";

export const GET_REPORT_BY_SELECTED_MONTH_REQUEST = "GET_REPORT_BY_SELECTED_MONTH_REQUEST";
export const GET_REPORT_BY_SELECTED_MONTH_SUCCESS = "GET_REPORT_BY_SELECTED_MONTH_SUCCESS";
export const GET_REPORT_BY_SELECTED_MONTH_FAILURE = "GET_REPORT_BY_SELECTED_MONTH_FAILURE";