export const GET_COMPANY_BY_ID_REQUEST = "GET_COMPANY_BY_ID_REQUEST";
export const GET_COMPANY_BY_ID_SUCCESS = "GET_COMPANY_BY_ID_SUCCESS";
export const GET_COMPANY_BY_ID_FAILURE = "GET_COMPANY_BY_ID_FAILURE";

export const GET_COMPANY_BY_USER_ID_REQUEST = "GET_COMPANY_BY_USER_ID_REQUEST";
export const GET_COMPANY_BY_USER_ID_SUCCESS = "GET_COMPANY_BY_USER_ID_SUCCESS";
export const GET_COMPANY_BY_USER_ID_FAILURE = "GET_COMPANY_BY_USER_ID_FAILURE";

export const GET_COMPANY_BY_EMPLOYEE_ID_REQUEST = "GET_COMPANY_BY_EMPLOYEE_ID_REQUEST";
export const GET_COMPANY_BY_EMPLOYEE_ID_SUCCESS = "GET_COMPANY_BY_EMPLOYEE_ID_SUCCESS";
export const GET_COMPANY_BY_EMPLOYEE_ID_FAILURE = "GET_COMPANY_BY_EMPLOYEE_ID_FAILURE";

export const GET_ALL_COMPANIES_REQUEST = "GET_ALL_COMPANIES_REQUEST";
export const GET_ALL_COMPANIES_SUCCESS = "GET_ALL_COMPANIES_SUCCESS";
export const GET_ALL_COMPANIES_FAILURE = "GET_ALL_COMPANIES_FAILURE";

export const ACTIVATE_BASKET_REQUEST = "ACTIVATE_BASKET_REQUEST";
export const ACTIVATE_BASKET_SUCCESS = "ACTIVATE_BASKET_SUCCESS";
export const ACTIVATE_BASKET_FAILURE = "ACTIVATE_BASKET_FAILURE";

export const DEACTIVATE_BASKET_REQUEST = "DEACTIVATE_BASKET_REQUEST";
export const DEACTIVATE_BASKET_SUCCESS = "DEACTIVATE_BASKET_SUCCESS";
export const DEACTIVATE_BASKET_FAILURE = "DEACTIVATE_BASKET_FAILURE";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAILURE = "UPDATE_COMPANY_FAILURE";