export const GET_RECORD_ITEM_BY_ID_REQUEST = "GET_RECORD_ITEM_BY_ID_REQUEST";
export const GET_RECORD_ITEM_BY_ID_SUCCESS = "GET_RECORD_ITEM_BY_ID_SUCCESS";
export const GET_RECORD_ITEM_BY_ID_FAILURE = "GET_RECORD_ITEM_BY_ID_FAILURE";

export const GET_RECORD_ITEMS_BY_COMPANY_ID_REQUEST = "GET_RECORD_ITEMS_BY_COMPANY_ID_REQUEST";
export const GET_RECORD_ITEMS_BY_COMPANY_ID_SUCCESS = "GET_RECORD_ITEMS_BY_COMPANY_ID_SUCCESS";
export const GET_RECORD_ITEMS_BY_COMPANY_ID_FAILURE = "GET_RECORD_ITEMS_BY_COMPANY_ID_FAILURE";

export const GET_RECORD_ITEMS_BY_MONTH_REQUEST = "GET_RECORD_ITEMS_BY_MONTH_REQUEST";
export const GET_RECORD_ITEMS_BY_MONTH_SUCCESS = "GET_RECORD_ITEMS_BY_MONTH_SUCCESS";
export const GET_RECORD_ITEMS_BY_MONTH_FAILURE = "GET_RECORD_ITEMS_BY_MONTH_FAILURE";

export const GET_RECORD_ITEMS_BY_DAY_REQUEST = "GET_RECORD_ITEMS_BY_DAY_REQUEST";
export const GET_RECORD_ITEMS_BY_DAY_SUCCESS = "GET_RECORD_ITEMS_BY_DAY_SUCCESS";
export const GET_RECORD_ITEMS_BY_DAY_FAILURE = "GET_RECORD_ITEMS_BY_DAY_FAILURE";

export const CREATE_RECORD_ITEM_REQUEST = "CREATE_RECORD_ITEM_REQUEST";
export const CREATE_RECORD_ITEM_SUCCESS = "CREATE_RECORD_ITEM_SUCCESS";
export const CREATE_RECORD_ITEM_FAILURE = "CREATE_RECORD_ITEM_FAILURE";

export const UPDATE_RECORD_ITEM_REQUEST = "UPDATE_RECORD_ITEM_REQUEST";
export const UPDATE_RECORD_ITEM_SUCCESS = "UPDATE_RECORD_ITEM_SUCCESS";
export const UPDATE_RECORD_ITEM_FAILURE = "UPDATE_RECORD_ITEM_FAILURE";

export const DELETE_RECORD_ITEM_REQUEST = "DELETE_RECORD_ITEM_REQUEST";
export const DELETE_RECORD_ITEM_SUCCESS = "DELETE_RECORD_ITEM_SUCCESS";
export const DELETE_RECORD_ITEM_FAILURE = "DELETE_RECORD_ITEM_FAILURE";