export const CREATE_BASKET_REQUEST = "CREATE_BASKET_REQUEST";
export const CREATE_BASKET_SUCCESS = "CREATE_BASKET_SUCCESS";
export const CREATE_BASKET_FAILURE = "CREATE_BASKET_FAILURE";

export const UPDATE_BASKET_REQUEST = "UPDATE_BASKET_REQUEST";
export const UPDATE_BASKET_SUCCESS = "UPDATE_BASKET_SUCCESS";
export const UPDATE_BASKET_FAILURE = "UPDATE_BASKET_FAILURE";

export const DELETE_BASKET_REQUEST = "DELETE_BASKET_REQUEST";
export const DELETE_BASKET_SUCCESS = "DELETE_BASKET_SUCCESS";
export const DELETE_BASKET_FAILURE = "DELETE_BASKET_FAILURE";

export const GET_ALL_BASKETS_BY_COMPANY_ID_REQUEST = "GET_ALL_BASKETS_BY_COMPANY_ID_REQUEST";
export const GET_ALL_BASKETS_BY_COMPANY_ID_SUCCESS = "GET_ALL_BASKETS_BY_COMPANY_ID_SUCCESS";
export const GET_ALL_BASKETS_BY_COMPANY_ID_FAILURE = "GET_ALL_BASKETS_BY_COMPANY_ID_FAILURE";

export const GET_BASKET_BY_ID_REQUEST = "GET_BASKET_BY_ID_REQUEST";
export const GET_BASKET_BY_ID_SUCCESS = "GET_BASKET_BY_ID_SUCCESS";
export const GET_BASKET_BY_ID_FAILURE = "GET_BASKET_BY_ID_FAILURE";

export const ACTIVATE_BASKET_REQUEST = "ACTIVATE_BASKET_REQUEST";
export const ACTIVATE_BASKET_SUCCESS = "ACTIVATE_BASKET_SUCCESS";
export const ACTIVATE_BASKET_FAILURE = "ACTIVATE_BASKET_FAILURE";

export const DEACTIVATE_BASKET_REQUEST = "DEACTIVATE_BASKET_REQUEST";
export const DEACTIVATE_BASKET_SUCCESS = "DEACTIVATE_BASKET_SUCCESS";
export const DEACTIVATE_BASKET_FAILURE = "DEACTIVATE_BASKET_FAILURE";
